name: Frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Navigate to project directory
        run: cd /actions-runner/frontend/github-action-frontend/github-action-frontend

      - name: Install Dependencies
        run: |
          cd /actions-runner/frontend/github-action-frontend/github-action-frontend
          npm install  # Use `yarn install` if using Yarn
  
      - name: Build the Project
        run: |
          cd /actions-runner/frontend/github-action-frontend/github-action-frontend
          npm run build  # Adjust command based on your project setup

      - name: Restart Nginx
        run: sudo systemctl restart nginx
